# services:
#   # nginx_server:
#   #   container_name: nginx1
#   #   image: nginx:latest
#   #   ports:
#   #     - "80:80"
#   nginx_server:
#     container_name: nginx1
#     image: jprollins-nginx
#     build:
#       context: .
#       dockerfile: nginx1.dockerfile
#     ports:
#       - "80:80"
#
#   nginx_server2:
#     container_name: nginx2
#     image: nginx:latest
#     ports:
#       - "81:80"
#
# # docker compose build
# # docker compose up

services:
  app:
    container_name: nodeapp
    networks:
      - app-db-network
    links:
      - db
    depends_on:
      - db
  db:
    container_name: db
    networks:
      - app-db-network
    links:
      - nodeapp

networks:
  app-db-network:
    driver: bridge
